name: Integration Tests
on: [push]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get_repos
        uses: ./
        with:
          org: firebase
          pattern: ^quickstart.*$